GROQ_API_KEY = "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"
STABILITY_API_KEY = "sk-YivztYKeED0lRUedpsGXvy5axGf1icFHsI5egbJaRD3BTqwR"

[twitter]
API_KEY = "NrMRWtDQG0RIqjsKM31q1GEIm"
API_SECRET = "W2H3flD2LiZGkoDnOaauLo9HBLk0o8geZCiIVfIqalQINYJFg9"
ACCESS_TOKEN = "1744213289381265408-FfNR3R77LR4enjTAmnkktDTsgPwVTD"
ACCESS_TOKEN_SECRET = "eclnd4KAdHAD9prWTVNdbn1wMiubgV4hdRxaW9xZ1eMLa"

